# This is a basic workflow to help you get started with Actions

name: CI for spendwise

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
    
concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true
  # Allows you to run this workflow manually from the Actions tab
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-and-hello:
    name: Lint + Hello world
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello
        uses: echo "CI pipeline lives on {bharathravelli-419}/{spendwise}[/workflows/ci.yml]@{main}."

      - name: Check required Docs are presetn
        run: |
          test -f README.md
          test -f .gitignore
          test -f .editorconfig
          test -d docs/adr
          echo "Required files are present"
